### ISSUE TITLE
Clients not sending to eachother

### ISSUE THREAD

**Issue by caimen** [ninjasource/websocket-server#1]
So I opened up the project and ran it.  I open up two client.html pages in chrome.  They send to the server fine, but shouldn't the clients being seeing eachother's chat messages?  Have I done something wrong?

**Comment by ninjasource** [comment]
Hi, the example is a simple echo from the server. However you are free to keep track of all connected clients and broadcast to everyone when a message arrives. I kept the demo as simple as possible.
